// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY5gSojtBx_yc0tvObnRPemxLp9rg50Wo',
    appId: '1:435028376050:android:d219f7fb0fa1171020536b',
    messagingSenderId: '435028376050',
    projectId: 'jigyasa-b7499',
    storageBucket: 'jigyasa-b7499.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcoo1QFi6bT1ra-OvnuQns7x0O_f5rHKg',
    appId: '1:435028376050:ios:b7fa2bdc877b36f820536b',
    messagingSenderId: '435028376050',
    projectId: 'jigyasa-b7499',
    storageBucket: 'jigyasa-b7499.firebasestorage.app',
    androidClientId: '435028376050-4qdfmblbt6n1pq9bqg20mgbu7gkesb1r.apps.googleusercontent.com',
    iosClientId: '435028376050-tkva2db3vqct8866cakf7vg397g2tb1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.jigyasa',
  );
}
